apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
      managed-by: deployment
  template:
    metadata:
      labels:
        app: service-a
        managed-by: deployment
    spec:
      containers:
      - name: service-a
        image: yosefshoval/service-a:v1
        ports:
        - containerPort: 8000
        env:
        - name: API_KEY
          value: 5F67eMEeTFUlPaewp4z6JeMQsu83klkB
        - name: SERVICE_B_IP
          value: "db-api"
        - name: SERVICE_B_PORT
          value: '8000'